//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ForecastingBatch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ForecastingBatch">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="expired" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="expiryDate" type="{http://www.msh.org/quantb/model/forecast}Month"/>
 *         <element name="quantity" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="quantityAvailable" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="quantityExpired" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="consumptionInMonth" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="availFrom" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="exclude" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="gdf" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForecastingBatch", propOrder = {
    "expired",
    "expiryDate",
    "quantity",
    "comment",
    "quantityAvailable",
    "quantityExpired",
    "consumptionInMonth",
    "availFrom",
    "exclude",
    "gdf"
})
public class ForecastingBatch {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expired;
    @XmlElement(required = true)
    protected Month expiryDate;
    protected long quantity;
    @XmlElement(required = true)
    protected String comment;
    @XmlElement(required = true)
    protected BigDecimal quantityAvailable;
    protected long quantityExpired;
    @XmlElement(required = true)
    protected BigDecimal consumptionInMonth;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar availFrom;
    protected boolean exclude;
    protected boolean gdf;

    /**
     * Gets the value of the expired property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpired() {
        return expired;
    }

    /**
     * Sets the value of the expired property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpired(XMLGregorianCalendar value) {
        this.expired = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link Month }
     *     
     */
    public Month getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Month }
     *     
     */
    public void setExpiryDate(Month value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public long getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(long value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the quantityAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantityAvailable() {
        return quantityAvailable;
    }

    /**
     * Sets the value of the quantityAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantityAvailable(BigDecimal value) {
        this.quantityAvailable = value;
    }

    /**
     * Gets the value of the quantityExpired property.
     * 
     */
    public long getQuantityExpired() {
        return quantityExpired;
    }

    /**
     * Sets the value of the quantityExpired property.
     * 
     */
    public void setQuantityExpired(long value) {
        this.quantityExpired = value;
    }

    /**
     * Gets the value of the consumptionInMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConsumptionInMonth() {
        return consumptionInMonth;
    }

    /**
     * Sets the value of the consumptionInMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConsumptionInMonth(BigDecimal value) {
        this.consumptionInMonth = value;
    }

    /**
     * Gets the value of the availFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAvailFrom() {
        return availFrom;
    }

    /**
     * Sets the value of the availFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAvailFrom(XMLGregorianCalendar value) {
        this.availFrom = value;
    }

    /**
     * Gets the value of the exclude property.
     * 
     */
    public boolean isExclude() {
        return exclude;
    }

    /**
     * Sets the value of the exclude property.
     * 
     */
    public void setExclude(boolean value) {
        this.exclude = value;
    }

    /**
     * Gets the value of the gdf property.
     * 
     */
    public boolean isGdf() {
        return gdf;
    }

    /**
     * Sets the value of the gdf property.
     * 
     */
    public void setGdf(boolean value) {
        this.gdf = value;
    }

}
