//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ForecastingResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ForecastingResult">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="month" type="{http://www.msh.org/quantb/model/forecast}Month"/>
 *         <element name="fromDay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="toDay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="oldCases" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="newCases" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="consOld" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="consNew" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="missing" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="batches" type="{http://www.msh.org/quantb/model/forecast}ForecastingBatch" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="orders" type="{http://www.msh.org/quantb/model/forecast}ForecastingOrder" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForecastingResult", propOrder = {
    "month",
    "fromDay",
    "toDay",
    "oldCases",
    "newCases",
    "consOld",
    "consNew",
    "missing",
    "batches",
    "orders"
})
public class ForecastingResult {

    @XmlElement(required = true)
    protected Month month;
    protected int fromDay;
    protected int toDay;
    @XmlElement(required = true)
    protected BigDecimal oldCases;
    @XmlElement(required = true)
    protected BigDecimal newCases;
    @XmlElement(required = true)
    protected BigDecimal consOld;
    @XmlElement(required = true)
    protected BigDecimal consNew;
    @XmlElement(required = true)
    protected BigDecimal missing;
    protected List<ForecastingBatch> batches;
    protected List<ForecastingOrder> orders;

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link Month }
     *     
     */
    public Month getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link Month }
     *     
     */
    public void setMonth(Month value) {
        this.month = value;
    }

    /**
     * Gets the value of the fromDay property.
     * 
     */
    public int getFromDay() {
        return fromDay;
    }

    /**
     * Sets the value of the fromDay property.
     * 
     */
    public void setFromDay(int value) {
        this.fromDay = value;
    }

    /**
     * Gets the value of the toDay property.
     * 
     */
    public int getToDay() {
        return toDay;
    }

    /**
     * Sets the value of the toDay property.
     * 
     */
    public void setToDay(int value) {
        this.toDay = value;
    }

    /**
     * Gets the value of the oldCases property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOldCases() {
        return oldCases;
    }

    /**
     * Sets the value of the oldCases property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOldCases(BigDecimal value) {
        this.oldCases = value;
    }

    /**
     * Gets the value of the newCases property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNewCases() {
        return newCases;
    }

    /**
     * Sets the value of the newCases property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNewCases(BigDecimal value) {
        this.newCases = value;
    }

    /**
     * Gets the value of the consOld property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConsOld() {
        return consOld;
    }

    /**
     * Sets the value of the consOld property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConsOld(BigDecimal value) {
        this.consOld = value;
    }

    /**
     * Gets the value of the consNew property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConsNew() {
        return consNew;
    }

    /**
     * Sets the value of the consNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConsNew(BigDecimal value) {
        this.consNew = value;
    }

    /**
     * Gets the value of the missing property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMissing() {
        return missing;
    }

    /**
     * Sets the value of the missing property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMissing(BigDecimal value) {
        this.missing = value;
    }

    /**
     * Gets the value of the batches property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the batches property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatches().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastingBatch }
     * 
     * 
     * @return
     *     The value of the batches property.
     */
    public List<ForecastingBatch> getBatches() {
        if (batches == null) {
            batches = new ArrayList<>();
        }
        return this.batches;
    }

    /**
     * Gets the value of the orders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the orders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastingOrder }
     * 
     * 
     * @return
     *     The value of the orders property.
     */
    public List<ForecastingOrder> getOrders() {
        if (orders == null) {
            orders = new ArrayList<>();
        }
        return this.orders;
    }

}
