//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ForecastingOrder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ForecastingOrder">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="arrived" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="arrivalDate" type="{http://www.msh.org/quantb/model/forecast}Month"/>
 *         <element name="batch" type="{http://www.msh.org/quantb/model/forecast}ForecastingBatch"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForecastingOrder", propOrder = {
    "arrived",
    "arrivalDate",
    "batch"
})
public class ForecastingOrder {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar arrived;
    @XmlElement(required = true)
    protected Month arrivalDate;
    @XmlElement(required = true)
    protected ForecastingBatch batch;

    /**
     * Gets the value of the arrived property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrived() {
        return arrived;
    }

    /**
     * Sets the value of the arrived property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrived(XMLGregorianCalendar value) {
        this.arrived = value;
    }

    /**
     * Gets the value of the arrivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link Month }
     *     
     */
    public Month getArrivalDate() {
        return arrivalDate;
    }

    /**
     * Sets the value of the arrivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Month }
     *     
     */
    public void setArrivalDate(Month value) {
        this.arrivalDate = value;
    }

    /**
     * Gets the value of the batch property.
     * 
     * @return
     *     possible object is
     *     {@link ForecastingBatch }
     *     
     */
    public ForecastingBatch getBatch() {
        return batch;
    }

    /**
     * Sets the value of the batch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForecastingBatch }
     *     
     */
    public void setBatch(ForecastingBatch value) {
        this.batch = value;
    }

}
