//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Forecast for a regimen. Included to ForecastingRegimenResult. Medicines needs and cases quantity by phases of the regimen. 
 * 
 * <p>Java class for ForecastingRegimenResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ForecastingRegimenResult">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="month" type="{http://www.msh.org/quantb/model/forecast}Month"/>
 *         <element name="fromDay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="toDay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="intensive" type="{http://www.msh.org/quantb/model/forecast}PhaseResult"/>
 *         <element name="continious" type="{http://www.msh.org/quantb/model/forecast}PhaseResult"/>
 *         <element name="addPhases" type="{http://www.msh.org/quantb/model/forecast}PhaseResult" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="weekList" type="{http://www.msh.org/quantb/model/forecast}WeekQuantity" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="cons" type="{http://www.msh.org/quantb/model/forecast}MedicineCons" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForecastingRegimenResult", propOrder = {
    "month",
    "fromDay",
    "toDay",
    "intensive",
    "continious",
    "addPhases",
    "weekList",
    "cons"
})
public class ForecastingRegimenResult {

    @XmlElement(required = true)
    protected Month month;
    protected int fromDay;
    protected int toDay;
    @XmlElement(required = true)
    protected PhaseResult intensive;
    @XmlElement(required = true)
    protected PhaseResult continious;
    protected List<PhaseResult> addPhases;
    protected List<WeekQuantity> weekList;
    protected List<MedicineCons> cons;

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link Month }
     *     
     */
    public Month getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link Month }
     *     
     */
    public void setMonth(Month value) {
        this.month = value;
    }

    /**
     * Gets the value of the fromDay property.
     * 
     */
    public int getFromDay() {
        return fromDay;
    }

    /**
     * Sets the value of the fromDay property.
     * 
     */
    public void setFromDay(int value) {
        this.fromDay = value;
    }

    /**
     * Gets the value of the toDay property.
     * 
     */
    public int getToDay() {
        return toDay;
    }

    /**
     * Sets the value of the toDay property.
     * 
     */
    public void setToDay(int value) {
        this.toDay = value;
    }

    /**
     * Gets the value of the intensive property.
     * 
     * @return
     *     possible object is
     *     {@link PhaseResult }
     *     
     */
    public PhaseResult getIntensive() {
        return intensive;
    }

    /**
     * Sets the value of the intensive property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhaseResult }
     *     
     */
    public void setIntensive(PhaseResult value) {
        this.intensive = value;
    }

    /**
     * Gets the value of the continious property.
     * 
     * @return
     *     possible object is
     *     {@link PhaseResult }
     *     
     */
    public PhaseResult getContinious() {
        return continious;
    }

    /**
     * Sets the value of the continious property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhaseResult }
     *     
     */
    public void setContinious(PhaseResult value) {
        this.continious = value;
    }

    /**
     * Gets the value of the addPhases property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the addPhases property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddPhases().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhaseResult }
     * 
     * 
     * @return
     *     The value of the addPhases property.
     */
    public List<PhaseResult> getAddPhases() {
        if (addPhases == null) {
            addPhases = new ArrayList<>();
        }
        return this.addPhases;
    }

    /**
     * Gets the value of the weekList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the weekList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWeekList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WeekQuantity }
     * 
     * 
     * @return
     *     The value of the weekList property.
     */
    public List<WeekQuantity> getWeekList() {
        if (weekList == null) {
            weekList = new ArrayList<>();
        }
        return this.weekList;
    }

    /**
     * Gets the value of the cons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the cons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicineCons }
     * 
     * 
     * @return
     *     The value of the cons property.
     */
    public List<MedicineCons> getCons() {
        if (cons == null) {
            cons = new ArrayList<>();
        }
        return this.cons;
    }

}
