//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.msh.quantb.model.gen.Medicine;


/**
 * Medicine parameters and result of forecasting
 * 			
 * 
 * <p>Java class for ForecastingMedicine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ForecastingMedicine">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="medicine" type="{http://www.msh.org/quantb/model/gen}Medicine"/>
 *         <element name="stockOnOrderLT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="consumptionLT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="quantityMissingLT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="quantityExpiredLT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="consumptionCases" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="consumptionNewCases" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="unitPrice" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="stockOnHand" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="batchesToExpire" type="{http://www.msh.org/quantb/model/forecast}ForecastingBatch" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="orders" type="{http://www.msh.org/quantb/model/forecast}ForecastingOrder" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="results" type="{http://www.msh.org/quantb/model/forecast}ForecastingResult" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="packOrder" type="{http://www.msh.org/quantb/model/forecast}PricePack" minOccurs="0"/>
 *         <element name="ajustmentEnrolled" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="adjustmentExpected" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForecastingMedicine", propOrder = {
    "medicine",
    "stockOnOrderLT",
    "consumptionLT",
    "quantityMissingLT",
    "quantityExpiredLT",
    "consumptionCases",
    "consumptionNewCases",
    "unitPrice",
    "stockOnHand",
    "batchesToExpire",
    "orders",
    "results",
    "packOrder",
    "ajustmentEnrolled",
    "adjustmentExpected"
})
public class ForecastingMedicine {

    @XmlElement(required = true)
    protected Medicine medicine;
    protected long stockOnOrderLT;
    protected long consumptionLT;
    protected long quantityMissingLT;
    protected long quantityExpiredLT;
    protected long consumptionCases;
    protected long consumptionNewCases;
    protected int unitPrice;
    protected long stockOnHand;
    protected List<ForecastingBatch> batchesToExpire;
    protected List<ForecastingOrder> orders;
    protected List<ForecastingResult> results;
    protected PricePack packOrder;
    @XmlElement(required = true)
    protected BigDecimal ajustmentEnrolled;
    @XmlElement(required = true)
    protected BigDecimal adjustmentExpected;

    /**
     * Gets the value of the medicine property.
     * 
     * @return
     *     possible object is
     *     {@link Medicine }
     *     
     */
    public Medicine getMedicine() {
        return medicine;
    }

    /**
     * Sets the value of the medicine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Medicine }
     *     
     */
    public void setMedicine(Medicine value) {
        this.medicine = value;
    }

    /**
     * Gets the value of the stockOnOrderLT property.
     * 
     */
    public long getStockOnOrderLT() {
        return stockOnOrderLT;
    }

    /**
     * Sets the value of the stockOnOrderLT property.
     * 
     */
    public void setStockOnOrderLT(long value) {
        this.stockOnOrderLT = value;
    }

    /**
     * Gets the value of the consumptionLT property.
     * 
     */
    public long getConsumptionLT() {
        return consumptionLT;
    }

    /**
     * Sets the value of the consumptionLT property.
     * 
     */
    public void setConsumptionLT(long value) {
        this.consumptionLT = value;
    }

    /**
     * Gets the value of the quantityMissingLT property.
     * 
     */
    public long getQuantityMissingLT() {
        return quantityMissingLT;
    }

    /**
     * Sets the value of the quantityMissingLT property.
     * 
     */
    public void setQuantityMissingLT(long value) {
        this.quantityMissingLT = value;
    }

    /**
     * Gets the value of the quantityExpiredLT property.
     * 
     */
    public long getQuantityExpiredLT() {
        return quantityExpiredLT;
    }

    /**
     * Sets the value of the quantityExpiredLT property.
     * 
     */
    public void setQuantityExpiredLT(long value) {
        this.quantityExpiredLT = value;
    }

    /**
     * Gets the value of the consumptionCases property.
     * 
     */
    public long getConsumptionCases() {
        return consumptionCases;
    }

    /**
     * Sets the value of the consumptionCases property.
     * 
     */
    public void setConsumptionCases(long value) {
        this.consumptionCases = value;
    }

    /**
     * Gets the value of the consumptionNewCases property.
     * 
     */
    public long getConsumptionNewCases() {
        return consumptionNewCases;
    }

    /**
     * Sets the value of the consumptionNewCases property.
     * 
     */
    public void setConsumptionNewCases(long value) {
        this.consumptionNewCases = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     */
    public int getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     */
    public void setUnitPrice(int value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the stockOnHand property.
     * 
     */
    public long getStockOnHand() {
        return stockOnHand;
    }

    /**
     * Sets the value of the stockOnHand property.
     * 
     */
    public void setStockOnHand(long value) {
        this.stockOnHand = value;
    }

    /**
     * Gets the value of the batchesToExpire property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the batchesToExpire property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatchesToExpire().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastingBatch }
     * 
     * 
     * @return
     *     The value of the batchesToExpire property.
     */
    public List<ForecastingBatch> getBatchesToExpire() {
        if (batchesToExpire == null) {
            batchesToExpire = new ArrayList<>();
        }
        return this.batchesToExpire;
    }

    /**
     * Gets the value of the orders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the orders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastingOrder }
     * 
     * 
     * @return
     *     The value of the orders property.
     */
    public List<ForecastingOrder> getOrders() {
        if (orders == null) {
            orders = new ArrayList<>();
        }
        return this.orders;
    }

    /**
     * Gets the value of the results property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the results property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResults().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastingResult }
     * 
     * 
     * @return
     *     The value of the results property.
     */
    public List<ForecastingResult> getResults() {
        if (results == null) {
            results = new ArrayList<>();
        }
        return this.results;
    }

    /**
     * Gets the value of the packOrder property.
     * 
     * @return
     *     possible object is
     *     {@link PricePack }
     *     
     */
    public PricePack getPackOrder() {
        return packOrder;
    }

    /**
     * Sets the value of the packOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricePack }
     *     
     */
    public void setPackOrder(PricePack value) {
        this.packOrder = value;
    }

    /**
     * Gets the value of the ajustmentEnrolled property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAjustmentEnrolled() {
        return ajustmentEnrolled;
    }

    /**
     * Sets the value of the ajustmentEnrolled property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAjustmentEnrolled(BigDecimal value) {
        this.ajustmentEnrolled = value;
    }

    /**
     * Gets the value of the adjustmentExpected property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdjustmentExpected() {
        return adjustmentExpected;
    }

    /**
     * Sets the value of the adjustmentExpected property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdjustmentExpected(BigDecimal value) {
        this.adjustmentExpected = value;
    }

}
