//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KitDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="KitDefinition">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="kitName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="inventory" type="{http://www.msh.org/quantb/model/forecast}ForecastingBatch" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="orders" type="{http://www.msh.org/quantb/model/forecast}ForecastingOrder" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KitDefinition", propOrder = {
    "kitName",
    "inventory",
    "orders"
})
public class KitDefinition {

    @XmlElement(required = true)
    protected String kitName;
    protected List<ForecastingBatch> inventory;
    protected List<ForecastingOrder> orders;

    /**
     * Gets the value of the kitName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKitName() {
        return kitName;
    }

    /**
     * Sets the value of the kitName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKitName(String value) {
        this.kitName = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the inventory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInventory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastingBatch }
     * 
     * 
     * @return
     *     The value of the inventory property.
     */
    public List<ForecastingBatch> getInventory() {
        if (inventory == null) {
            inventory = new ArrayList<>();
        }
        return this.inventory;
    }

    /**
     * Gets the value of the orders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the orders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastingOrder }
     * 
     * 
     * @return
     *     The value of the orders property.
     */
    public List<ForecastingOrder> getOrders() {
        if (orders == null) {
            orders = new ArrayList<>();
        }
        return this.orders;
    }

}
