//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.msh.quantb.model.gen.Medicine;


/**
 * Consumption of a medicine in a Forecasting Result.
 * 
 * <p>Java class for MedicineCons complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="MedicineCons">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="medicine" type="{http://www.msh.org/quantb/model/gen}Medicine"/>
 *         <element name="consIntensiveOld" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="consContiOld" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="consIntensiveNew" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="consContiNew" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="consOtherOld" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="consOtherNew" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicineCons", propOrder = {
    "medicine",
    "consIntensiveOld",
    "consContiOld",
    "consIntensiveNew",
    "consContiNew",
    "consOtherOld",
    "consOtherNew"
})
public class MedicineCons {

    @XmlElement(required = true)
    protected Medicine medicine;
    @XmlElement(required = true)
    protected BigDecimal consIntensiveOld;
    @XmlElement(required = true)
    protected BigDecimal consContiOld;
    @XmlElement(required = true)
    protected BigDecimal consIntensiveNew;
    @XmlElement(required = true)
    protected BigDecimal consContiNew;
    protected List<BigDecimal> consOtherOld;
    protected List<BigDecimal> consOtherNew;

    /**
     * Gets the value of the medicine property.
     * 
     * @return
     *     possible object is
     *     {@link Medicine }
     *     
     */
    public Medicine getMedicine() {
        return medicine;
    }

    /**
     * Sets the value of the medicine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Medicine }
     *     
     */
    public void setMedicine(Medicine value) {
        this.medicine = value;
    }

    /**
     * Gets the value of the consIntensiveOld property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConsIntensiveOld() {
        return consIntensiveOld;
    }

    /**
     * Sets the value of the consIntensiveOld property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConsIntensiveOld(BigDecimal value) {
        this.consIntensiveOld = value;
    }

    /**
     * Gets the value of the consContiOld property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConsContiOld() {
        return consContiOld;
    }

    /**
     * Sets the value of the consContiOld property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConsContiOld(BigDecimal value) {
        this.consContiOld = value;
    }

    /**
     * Gets the value of the consIntensiveNew property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConsIntensiveNew() {
        return consIntensiveNew;
    }

    /**
     * Sets the value of the consIntensiveNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConsIntensiveNew(BigDecimal value) {
        this.consIntensiveNew = value;
    }

    /**
     * Gets the value of the consContiNew property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConsContiNew() {
        return consContiNew;
    }

    /**
     * Sets the value of the consContiNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConsContiNew(BigDecimal value) {
        this.consContiNew = value;
    }

    /**
     * Gets the value of the consOtherOld property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the consOtherOld property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConsOtherOld().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     * @return
     *     The value of the consOtherOld property.
     */
    public List<BigDecimal> getConsOtherOld() {
        if (consOtherOld == null) {
            consOtherOld = new ArrayList<>();
        }
        return this.consOtherOld;
    }

    /**
     * Gets the value of the consOtherNew property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the consOtherNew property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConsOtherNew().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     * @return
     *     The value of the consOtherNew property.
     */
    public List<BigDecimal> getConsOtherNew() {
        if (consOtherNew == null) {
            consOtherNew = new ArrayList<>();
        }
        return this.consOtherNew;
    }

}
