//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Quantity of enrolled or expected cases in a month given.
 * 
 * <p>Java class for MonthQuantity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="MonthQuantity">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="iQuantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="month" type="{http://www.msh.org/quantb/model/forecast}Month"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MonthQuantity", propOrder = {
    "iQuantity",
    "month"
})
public class MonthQuantity {

    protected int iQuantity;
    @XmlElement(required = true)
    protected Month month;

    /**
     * Gets the value of the iQuantity property.
     * 
     */
    public int getIQuantity() {
        return iQuantity;
    }

    /**
     * Sets the value of the iQuantity property.
     * 
     */
    public void setIQuantity(int value) {
        this.iQuantity = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link Month }
     *     
     */
    public Month getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link Month }
     *     
     */
    public void setMonth(Month value) {
        this.month = value;
    }

}
