//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.msh.quantb.model.forecast package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Forecast_QNAME = new QName("http://www.msh.org/quantb/model/forecast", "forecast");
    private static final QName _ForecastLast5_QNAME = new QName("http://www.msh.org/quantb/model/forecast", "forecastLast5");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.msh.quantb.model.forecast
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Forecast }
     * 
     * @return
     *     the new instance of {@link Forecast }
     */
    public Forecast createForecast() {
        return new Forecast();
    }

    /**
     * Create an instance of {@link ForecastLast5 }
     * 
     * @return
     *     the new instance of {@link ForecastLast5 }
     */
    public ForecastLast5 createForecastLast5() {
        return new ForecastLast5();
    }

    /**
     * Create an instance of {@link ForecastingRegimen }
     * 
     * @return
     *     the new instance of {@link ForecastingRegimen }
     */
    public ForecastingRegimen createForecastingRegimen() {
        return new ForecastingRegimen();
    }

    /**
     * Create an instance of {@link MonthQuantity }
     * 
     * @return
     *     the new instance of {@link MonthQuantity }
     */
    public MonthQuantity createMonthQuantity() {
        return new MonthQuantity();
    }

    /**
     * Create an instance of {@link ForecastingMedicine }
     * 
     * @return
     *     the new instance of {@link ForecastingMedicine }
     */
    public ForecastingMedicine createForecastingMedicine() {
        return new ForecastingMedicine();
    }

    /**
     * Create an instance of {@link Month }
     * 
     * @return
     *     the new instance of {@link Month }
     */
    public Month createMonth() {
        return new Month();
    }

    /**
     * Create an instance of {@link ForecastingResult }
     * 
     * @return
     *     the new instance of {@link ForecastingResult }
     */
    public ForecastingResult createForecastingResult() {
        return new ForecastingResult();
    }

    /**
     * Create an instance of {@link ForecastingBatch }
     * 
     * @return
     *     the new instance of {@link ForecastingBatch }
     */
    public ForecastingBatch createForecastingBatch() {
        return new ForecastingBatch();
    }

    /**
     * Create an instance of {@link ForecastingRegimenResult }
     * 
     * @return
     *     the new instance of {@link ForecastingRegimenResult }
     */
    public ForecastingRegimenResult createForecastingRegimenResult() {
        return new ForecastingRegimenResult();
    }

    /**
     * Create an instance of {@link ForecastingOrder }
     * 
     * @return
     *     the new instance of {@link ForecastingOrder }
     */
    public ForecastingOrder createForecastingOrder() {
        return new ForecastingOrder();
    }

    /**
     * Create an instance of {@link PhaseResult }
     * 
     * @return
     *     the new instance of {@link PhaseResult }
     */
    public PhaseResult createPhaseResult() {
        return new PhaseResult();
    }

    /**
     * Create an instance of {@link MedicineCons }
     * 
     * @return
     *     the new instance of {@link MedicineCons }
     */
    public MedicineCons createMedicineCons() {
        return new MedicineCons();
    }

    /**
     * Create an instance of {@link PricePack }
     * 
     * @return
     *     the new instance of {@link PricePack }
     */
    public PricePack createPricePack() {
        return new PricePack();
    }

    /**
     * Create an instance of {@link ForecastingTotalItem }
     * 
     * @return
     *     the new instance of {@link ForecastingTotalItem }
     */
    public ForecastingTotalItem createForecastingTotalItem() {
        return new ForecastingTotalItem();
    }

    /**
     * Create an instance of {@link WeekQuantity }
     * 
     * @return
     *     the new instance of {@link WeekQuantity }
     */
    public WeekQuantity createWeekQuantity() {
        return new WeekQuantity();
    }

    /**
     * Create an instance of {@link ForecastFile }
     * 
     * @return
     *     the new instance of {@link ForecastFile }
     */
    public ForecastFile createForecastFile() {
        return new ForecastFile();
    }

    /**
     * Create an instance of {@link KitDefinition }
     * 
     * @return
     *     the new instance of {@link KitDefinition }
     */
    public KitDefinition createKitDefinition() {
        return new KitDefinition();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Forecast }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Forecast }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.msh.org/quantb/model/forecast", name = "forecast")
    public JAXBElement<Forecast> createForecast(Forecast value) {
        return new JAXBElement<>(_Forecast_QNAME, Forecast.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForecastLast5 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ForecastLast5 }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.msh.org/quantb/model/forecast", name = "forecastLast5")
    public JAXBElement<ForecastLast5> createForecastLast5(ForecastLast5 value) {
        return new JAXBElement<>(_ForecastLast5_QNAME, ForecastLast5 .class, null, value);
    }

}
