//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Prospected cases in a phase of a regimen.
 * 
 * <p>Java class for PhaseResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="PhaseResult">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="newCases" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="oldCases" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhaseResult", propOrder = {
    "newCases",
    "oldCases"
})
public class PhaseResult {

    @XmlElement(required = true)
    protected BigDecimal newCases;
    @XmlElement(required = true)
    protected BigDecimal oldCases;

    /**
     * Gets the value of the newCases property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNewCases() {
        return newCases;
    }

    /**
     * Sets the value of the newCases property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNewCases(BigDecimal value) {
        this.newCases = value;
    }

    /**
     * Gets the value of the oldCases property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOldCases() {
        return oldCases;
    }

    /**
     * Sets the value of the oldCases property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOldCases(BigDecimal value) {
        this.oldCases = value;
    }

}
