//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.forecast;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Deprecated and outdated.
 * 
 * <p>Java class for WeekQuantity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="WeekQuantity">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="weekNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="newQuantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeekQuantity", propOrder = {
    "weekNo",
    "quantity",
    "newQuantity"
})
public class WeekQuantity {

    protected int weekNo;
    protected int quantity;
    protected int newQuantity;

    /**
     * Gets the value of the weekNo property.
     * 
     */
    public int getWeekNo() {
        return weekNo;
    }

    /**
     * Sets the value of the weekNo property.
     * 
     */
    public void setWeekNo(int value) {
        this.weekNo = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the newQuantity property.
     * 
     */
    public int getNewQuantity() {
        return newQuantity;
    }

    /**
     * Sets the value of the newQuantity property.
     * 
     */
    public void setNewQuantity(int value) {
        this.newQuantity = value;
    }

}
