//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.msh.quantb.model.locale;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for localeSaved complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="localeSaved">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="doNotShowHelp" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="pathToFiles" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "localeSaved", propOrder = {
    "country",
    "lang",
    "doNotShowHelp",
    "pathToFiles"
})
public class LocaleSaved {

    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected String lang;
    protected boolean doNotShowHelp;
    @XmlElement(required = true)
    protected String pathToFiles;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the doNotShowHelp property.
     * 
     */
    public boolean isDoNotShowHelp() {
        return doNotShowHelp;
    }

    /**
     * Sets the value of the doNotShowHelp property.
     * 
     */
    public void setDoNotShowHelp(boolean value) {
        this.doNotShowHelp = value;
    }

    /**
     * Gets the value of the pathToFiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathToFiles() {
        return pathToFiles;
    }

    /**
     * Sets the value of the pathToFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathToFiles(String value) {
        this.pathToFiles = value;
    }

}
